// hooks
import { useState } from 'react';

// our own API functions
import { getReviews } from './api/movies';

// nextjs components
import Head from 'next/head'

// MUI components
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// our own components
import ReviewCard from './components/ReviewCard';
import ReviewForm from './components/ReviewForm';


export default function Home() {

  const [reviews, setReviews] = useState([])


  const loadReviews = () => {
    getReviews().then((moviesData) => {
      setReviews(moviesData)
    })
  }

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

      <main>
        <Container maxWidth="md">

          {/* Look how clean & legible our main page is now! */}
          <ReviewForm
            reviews={reviews}
            onReviewsChange={setReviews}
          />

          {/* I could also pop this in the form, since technically it's also input behaviour.
              We'll start next class with that!
          */}
          <Box sx={{pt: 2, pb: 2 }}>
            <Button
              variant="contained"
              onClick={loadReviews}
            >
              Load All Current Reviews
            </Button>
          </Box>

          {reviews.map((adaptation, index)=> {
            return <ReviewCard
              key={index}
              title={adaptation.title}
              comments={adaptation.comment}
              rating={adaptation.rating}
            />
          })}

        </Container>
      </main>

    </div>
  )
}
