// hooks
import { useState } from 'react';

// nextjs components
import Head from 'next/head'

// MUI components
import AppBar from '@mui/material/AppBar';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// our own components
import ReviewCard from './components/ReviewCard';
import ReviewForm from './components/ReviewForm';


export default function Home() {

  const [reviews, setReviews] = useState([])

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

      <main>
        <Container maxWidth="md">

          {/* Look how clean & legible our main page is now! */}
          <ReviewForm
            reviews={reviews}
            onReviewsChange={setReviews}
          />

          {reviews.map((adaptation, index)=> {
            return <ReviewCard
              key={index}
              title={adaptation.title}
              comments={adaptation.comment}
              rating={adaptation.rating}
            />
          })}

        </Container>
      </main>

    </div>
  )
}
