// hooks
import { useState } from 'react';

// nextjs components
import Head from 'next/head'

// MUI components
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import InputLabel from '@mui/material/InputLabel';
import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';


import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// our own components
import ReviewCard from './components/ReviewCard';


const API_BASE_URL = 'http://localhost:5000' 


export default function Home() {

  const [title, setTitle]       = useState("")
  const [comments, setComments] = useState("")
  const [rating, setRating]     = useState(0)

  const [reviews, setReviews] = useState([])


  const loadReviews = () => {
    fetch(`${API_BASE_URL}/reviews`) // made my request
      .then((response) => {
        return response.json()  // parsed JSON of response into JS objectss
      }).then((data) => {
        setReviews(data)
      })
  }


  const submitReview = (event) => {
    event.preventDefault();
    fetch(`http://localhost:5000/reviews`,
      // we can also pass an object of various specifics as the 2nd param for fetch:
      {
        method: "POST",
        headers: {
          'Content-Type': 'application/json'
        },
        // because we're sending data to a REST API, we encode it as JSON; this is
        // a language-agnostic format. APIs don't necessarily know about JS objects!
        body: JSON.stringify(
          {
            // notice how for JSON.stringify, we can just declare the variable
            // if its name matches the JSON field
            title,
            // in this case, it's slightly different, so I have to do field: varName
            comment: comments,
            rating
          }
        )
      }
    ).then((response)=> {
      return response.json()
    }).then((movie)=> {
      // when we POST and create something anew, usually a (well-configured) REST API
      // sends us back a body response with the thing we just created.

      // in this example, we're letting the API data control what we render for front-end.
      // when we get body response back from item we created, use it to update state we render from!
      // state -> API -> state doesn't have to be strictly coupled like this (for example, I could just
      // watch for a 201 status code (created successfully) and just update 'reviews' with the local state
      // data, but I want to show you 'data journey' & POST request/response behaviour in this example).

      setReviews([movie, ...reviews]) // compose new array w/ newly created item -> trigger re-render 
      resetForm();
    })
  }

  const resetForm = () => {
    setTitle("")
    setComments("")
    setRating(0)
  }

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

      <main>
        <Container maxWidth="md">

          <form
            onSubmit={submitReview}
          >

            <Grid container spacing={3}>

              <Grid item xs={12} sm={12}>
                <TextField
                  id="title"
                  name="title"
                  label="Adaptation Title"
                  fullWidth
                  variant="standard"
                  value={title}
                  onChange={(e) => {setTitle(e.target.value)}}
                />
              </Grid>

              <Grid item xs={12} sm={12}>
                <TextField
                  id="review-comments"
                  name="review-comments"
                  label="Comments"
                  fullWidth
                  variant="standard"
                  value={comments}
                  onChange={(e) => {setComments(e.target.value)}}
                />
              </Grid>

              <Grid item xs={12} sm={12}>
                <FormControl>
                  <FormLabel id="adaptation-rating">Rating</FormLabel>
                  <RadioGroup
                    row
                    aria-labelledby="adaptation-rating"
                    name="rating-buttons-group"
                    value={rating}
                    onChange={(e) => {setRating(parseInt(e.target.value))}}
                  >
                    <FormControlLabel value="1" control={<Radio />} label="1" />
                    <FormControlLabel value="2" control={<Radio />} label="2" />
                    <FormControlLabel value="3" control={<Radio />} label="3" />
                    <FormControlLabel value="4" control={<Radio />} label="4" />
                    <FormControlLabel value="5" control={<Radio />} label="5" />
                    <FormControlLabel value="6" control={<Radio />} label="6" />
                    <FormControlLabel value="7" control={<Radio />} label="7" />
                    <FormControlLabel value="8" control={<Radio />} label="8" />
                    <FormControlLabel value="9" control={<Radio />} label="9" />
                    <FormControlLabel value="10" control={<Radio />} label="10" />
                  </RadioGroup>
               </FormControl>
              </Grid>

              <Grid item xs={12} sm={12}>
                <Button
                  variant="contained"
                  type="submit"
                >
                  Add New Review
                </Button>
              </Grid>

            </Grid>

          </form>

          <Box
            sx={{
              pt: 2,
              pb: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadReviews}
            >
              Load All Current Reviews
            </Button>
          </Box>

          {reviews.map((adaptation, index)=> {
            return <ReviewCard
              key={index}
              title={adaptation.title}
              comments={adaptation.comment}
              rating={adaptation.rating}
            />
          })}

        </Container>
      </main>

    </div>
  )
}
