import { useEffect, useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {

  const QUOTE_API_URL = 'https://dummyjson.com/quotes/'

  // separate these out so I can exclude them from quote retrieval count
  const DEFAULT_QUOTE = "Quote here."
  const DEFAULT_AUTHOR = "Author here."

  const [numberOfQuotes, setNumberOfQuotes] = useState(0)

  const [quoteData, setQuoteData] = useState({
    quote: DEFAULT_QUOTE,
    author: DEFAULT_AUTHOR
  })

  const getRandomQuote = () => {
    fetch(`${QUOTE_API_URL}/random`)
      .then((response)=> {
        return response.json()
      }).then((data)=> {
        console.log(data)
        setQuoteData({
          quote: data.quote,
          author: data.author
        })
      })  
  }

  // load a quote from API when component mounts.
  useEffect(() => {
      getRandomQuote()
    }, []
    // comments in prev. commit — usually effects are written more tersely, like this!
  )

  // new effect to update count every time quote changes (except initial state, since that
  // is still technically counted as a state change that the effect will respond to)
  useEffect(
    () => {
      if (quoteData.quote !== DEFAULT_QUOTE && quoteData.author !== DEFAULT_AUTHOR) {
        // remember: if Strict Mode were set on (see next.config.js), this would fire double
        //           because strict mode fires effects twice to test any cleanup (if present).
        setNumberOfQuotes(numberOfQuotes + 1)
      }
    },

    [quoteData] // effect will re-fire every time quoteData changes
  )

  /* I told you that useEffect should 'only'/mainly be used to talk to external systems; it can be
     misused pretty easily. In this case, because the quote count updating *depends on* prior side-effecting
     behaviour from the REST API (i.e. do it only when we get new API data), it's fine!
  */

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getRandomQuote}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>

          <Typography
            sx={{pt: 8}}
            variant="h5"
            align="center"
            color="text.primary"
            paragraph
          >
            You have fetched {numberOfQuotes} quotes
          </Typography>

        </Container>
      </main>
    </div>
  )
}
