import { Box, Container, Typography } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="sm">
          this is outside of the Material UI Box component
          <Box sx={{ my:4, border: '1px dashed grey'}}>this text is inside a Material UI Box component
            <Typography>
              MUI looks good
            </Typography>
          </Box>
        </Container>
      </main>
    </>
  );
}
