// react hooks
import { useState } from 'react';

// data
import { MOVIE_LIST } from '../utils/movies'

// MUI components
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';


export default function Home() {

  {/* [statefulValue, setStatefulValue] = useState(defaultValue) */}
  const [searchText, setSearchText] = useState("")
  const [year, setYear] = useState("")

  // this is just what we're displaying from
  const [movies, setMovies] = useState(MOVIE_LIST)

  // state variable for storing error message
  const [errorMsg, setErrorMsg] = useState("")

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(`search: ${searchText}`)
    console.log(`year: ${year}`)
    validateForm();
    filterMovies();
  }

  const isValidYear = (value) => {
    // Make sure the string value can resolve to a number, and that it's 4 digits,
    // 'cause they ain't makin' cinema in the age of Charlemagne.
    return !isNaN(year) && year.trim().length === 4
  }

  const validateForm = () => {
    /* The only validation I need to do here is making sure the year is OK.
       This means:
        1. If there's no input in the year field, there's gonna be no issue.
        2. If there is input, I need to make sure it's a valid number.
    */

    // 1. no input in year -> automatically pass check
    if (year.trim().length === 0) {
      // we'll be using a blank error message when all is OK to control conditional rendering
      setErrorMsg("");
      return
    }

    // 2.a) there is input in year field, but it's invalid
    if (!isValidYear(year)) {
      setErrorMsg(`${year} is not a valid year.`);
      return // escapes function block immediately
    }

    // 2.b) there is input in year field, and it's valid!
    //      -> this means we've already passed the check above, so nothing to do here except...
    setErrorMsg("")
  }

  const filterMovies = () => {
    /* Remember: React stateful variables are *immutable*, so I always need to
                completely reconstruct the value I want to write to pass to the setter.

                I can't e.g. push or pop from the 'movies' variable; it's immutable.
    */

    // 1. set up a new copy of the movies array
    let filteredMovies = [...MOVIE_LIST]

    // 2. if there's a search term, filter the copy array for that term
    if (searchText.trim()) {
      // I'm going to use [].filter() to reconstruct my array.
      // -> With [].filter(), only elements that pass the condition are included in the new array.
      // -> newArray = oldArray.filter((element) => {some condition})
      filteredMovies = filteredMovies.filter(
        (movie) => {
          // in [].filter(), you're returning *whether* something is true/truthy or false/falsey,
          // *not* specific values themselves.
          return movie.name.toLowerCase().includes(
            searchText.trim().toLowerCase()
          )
        }
      )
    }

    // 3. if there's a year, ditto
    if (year.trim()) {
      // I'm going to use [].filter() to reconstruct my array.
      // -> With [].filter(), only elements that pass the condition are included in the new array.
      // -> newArray = oldArray.filter((element) => {some condition})
      filteredMovies = filteredMovies.filter(
        (movie) => {
          return movie.year === parseInt(year.trim())
        }
      )
    }

    // 4. now that I've filtered my mutable, copied array based on inputs, I can
    //    pass that to the setter for the stateful movies variable.
    setMovies(filteredMovies)
  } 


  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          <form
            style={{width: '100%'}}
            onSubmit={handleSubmit}
          >
            <Grid container spacing={2}>
              {/* This uses an older version of MUI, specific to this package-lock.json,
                  hence the use of item & xs props.
              */}
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e) => setSearchText(e.target.value)}
                  value={searchText}
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e) => setYear(e.target.value)}
                  value={year}
                 
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                >Filter</Button>
              </Grid>
              <Grid item xs={10}>
                {/* Add the error message here

                    Again, I'm using && here because I want to show something here
                    *only if* there is an error.
                */}
                { errorMsg && 
                  <Alert severity="error">{errorMsg}</Alert>
                }
              </Grid>
            </Grid>
          </form>
          <List sx={{width: `100%`}}>
          {/* the && (AND) operator says, "if the first term resolves truthy, then do the next thing"
              In this case:  (movies doesn't have items -> show "no results found")

              The idea here is, always communicate to your user; don't just show nothing if data is empty.

              Using && is good when you don't have anything specific you need to do/render if the check *fails*.
              However, *if* you want to render "A" if the check passes, and "B" if the check fails, use a ternary:
                condition ? A : B
          */}
            <ListItem>
              <ListItemText>
               <Typography variant="p" component="div">
                { movies.length === 0 ?
                  "No results; please search again."
                  :
                  `Movies found: ${movies.length} `
                }
               </Typography>
              </ListItemText>
            </ListItem>
          { movies.map((movieData, index)=> {
              return <ListItem key={index}>
                <ListItemText>
                  <Typography variant="p" component="div">
                    {movieData.name} ({movieData.year})
                  </Typography>
                </ListItemText>
              </ListItem>
            })
          }
          </List>
        </Container>
      </main>
    </div>
  )
}
