import Head from "next/head";

// materialUI components
import Container from '@mui/material/Container';

// my components
import TodoList from './components/TodoList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="md">
          <TodoList />
        </Container>
      </main>

    </>
  );
}
